/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author pradyumnadas
 */
public class AddProfileDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddProfileDialog
     */
    public AddProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProfileName = new javax.swing.JTextField();
        fileAddPanel = new javax.swing.JPanel();
        srcFilesPanel = new javax.swing.JPanel();
        dstFilesPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Name");

        txtSrcFiles = new javax.swing.JTextField[7];
        txtDstFiles = new JTextField[7];
        cmdDstBrowse = new javax.swing.JButton[7];
        cmdSrcBrowse = new javax.swing.JButton[7];
        c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.insets = new Insets(5,0,0,0);
        for(int i=0;i<7;i++){
            cmdDstBrowse[i] = new JButton("Browse");
            cmdSrcBrowse[i] = new JButton("Browse");
        }
        fileAddPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Files to Sync"));

        srcFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Source Files"));
        srcFilesPanel.setLayout(new java.awt.GridBagLayout());

        for(int i = 0; i < 7; i++){
            c.gridx = 0;
            c.gridy = i;
            c.weightx = 1.0;
            txtSrcFiles[i] = new JTextField();
            srcFilesPanel.add(txtSrcFiles[i], c);
            c.gridx = 1;
            c.weightx = 0.05;
            srcFilesPanel.add(cmdSrcBrowse[i], c);

        }

        dstFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Destination Files"));
        dstFilesPanel.setLayout(new java.awt.GridBagLayout());

        for(int i = 0; i < 7; i++){
            c.gridx = 0;
            c.gridy = i;
            c.weightx = 1.0;
            txtDstFiles[i] = new JTextField();
            dstFilesPanel.add(txtDstFiles[i], c);
            c.gridx = 1;
            c.weightx = 0.05;
            dstFilesPanel.add(cmdDstBrowse[i], c);
        }

        javax.swing.GroupLayout fileAddPanelLayout = new javax.swing.GroupLayout(fileAddPanel);
        fileAddPanel.setLayout(fileAddPanelLayout);
        fileAddPanelLayout.setHorizontalGroup(
            fileAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileAddPanelLayout.createSequentialGroup()
                .addComponent(srcFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dstFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fileAddPanelLayout.setVerticalGroup(
            fileAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srcFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dstFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setText("OK");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfileName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 575, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fileAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dstFilesPanel;
    private javax.swing.JPanel fileAddPanel;
    private javax.swing.JTextField txtSrcFiles[];
    private javax.swing.JTextField txtDstFiles[];
    private javax.swing.JButton cmdDstBrowse[];
    private JButton cmdSrcBrowse[];
    private GridBagConstraints c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel srcFilesPanel;
    private javax.swing.JTextField txtProfileName;
    // End of variables declaration//GEN-END:variables
}
